# Generated by Django 5.2.7 on 2025-10-23 19:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='BlogInfo : CustomUser -> (1:1)', primary_key=True, serialize=False, unique=True)),
                ('blog_title', models.CharField(db_index=True, default='새로운 블로그', help_text='블로그 제목', max_length=20)),
                ('blog_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bloginfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='BlogInfo : BlogCategory -> (1:N)', primary_key=True, serialize=False, unique=True)),
                ('category_index', models.IntegerField(help_text='카테고리 정렬을 위해 사용되는 인덱스')),
                ('category_name', models.CharField(db_index=True, default='내 글', help_text='카테고리 이름', max_length=20)),
                ('category_isdepth', models.BooleanField(help_text='뎁스가 적용된 카테고리 여부 확인')),
                ('slug', models.SlugField(blank=True, help_text='카테고리 이름을 슬러그로 받음', max_length=100, unique=True)),
                ('category_depth_for', models.ForeignKey(blank=True, help_text='null시 부모', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='main.blogcategory')),
                ('category_for', models.ForeignKey(help_text='카테고리가 적용될 블로그 id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.bloginfo')),
            ],
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('post_id', models.IntegerField(auto_created=True, help_text='블로그 포스트 id', primary_key=True, serialize=False)),
                ('post_title', models.CharField(db_index=True, help_text='블로그 포스트 제목 필드', max_length=20)),
                ('post_contents', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='블로그 포스트 날짜')),
                ('post_editdate', models.DateTimeField(blank=True, help_text='블로그 포스트 수정된 날짜, 해당 필드에 값 유무로 포스트 수정 여부를 판단함', null=True)),
                ('slug', models.SlugField(blank=True, help_text='포스트 제목을 슬러그로 받음', max_length=100, unique=True)),
                ('post_blog', models.ForeignKey(help_text='포스트가 속한 블로그', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.bloginfo')),
                ('post_category', models.ForeignKey(blank=True, help_text='포스트가 속한 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('comment_index', models.IntegerField(auto_created=True, help_text='댓글 인덱스', primary_key=True, serialize=False)),
                ('comment_id', models.CharField(help_text='댓글 id', max_length=100)),
                ('comment_order', models.IntegerField(default=1, help_text='댓글/대댓글을 정렬하기 위한 순서이자 묶어주기 위한 그룹 대댓글의 경우 같은 order로 묶고 생성 날짜로 정렬한다')),
                ('comment_contents', models.TextField(help_text='댓글 내용')),
                ('comment_date', models.DateTimeField(auto_now_add=True, help_text='댓글 작성한 날짜')),
                ('comment_isreply', models.BooleanField(help_text='답글 여부 확인')),
                ('comment_isdelete', models.BooleanField(default=False, help_text='삭제 여부 확인')),
                ('comment_editor', models.ForeignKey(help_text='댓글 작성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='main.bloginfo')),
                ('comment_post', models.ForeignKey(help_text='댓글이 달린 포스트', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.postcontents')),
            ],
        ),
    ]
