# Generated by Django 5.1.4 on 2025-09-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('blog_id', models.CharField(help_text='블로그 id https://ex.com/blog/-------/', max_length=100, primary_key=True, serialize=False)),
                ('blog_title', models.CharField(db_index=True, help_text='블로그 제목', max_length=20)),
                ('blog_user', models.CharField(help_text='블로그 uid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('category_index', models.IntegerField(auto_created=True, help_text='카테고리 인덱스', primary_key=True, serialize=False)),
                ('category_id', models.CharField(help_text='카테고리 id', max_length=100)),
                ('category_name', models.CharField(db_index=True, default='내 글', help_text='카테고리 제목', max_length=20)),
                ('category_isdepth', models.BooleanField(help_text='뎁스가 적용된 카테고리 여부 확인')),
                ('category_depth_for', models.CharField(blank=True, help_text='뎁스가 적용된 카테고리의 부모 카테고리 id', max_length=100, null=True)),
                ('category_for', models.ForeignKey(help_text='카테고리가 적용될 블로그 id', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.bloginfo')),
            ],
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('post_id', models.IntegerField(auto_created=True, help_text='블로그 포스트 id', primary_key=True, serialize=False)),
                ('post_title', models.CharField(db_index=True, help_text='블로그 포스트 제목 필드', max_length=20)),
                ('post_contents', models.TextField(help_text='블로그 포스트 내용 필드')),
                ('post_date', models.DateTimeField(auto_now_add=True, help_text='블로그 포스트 날짜')),
                ('post_editdate', models.DateTimeField(help_text='블로그 포스트 수정된 날짜', null=True)),
                ('post_blog', models.ForeignKey(help_text='포스트가 속한 블로그', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='main.bloginfo')),
                ('post_category', models.ForeignKey(blank=True, help_text='포스트가 속한 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='main.blogcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('comment_index', models.IntegerField(auto_created=True, help_text='댓글 인덱스', primary_key=True, serialize=False)),
                ('comment_id', models.CharField(help_text='댓글 id', max_length=100)),
                ('comment_order', models.IntegerField(default=1, help_text='댓글/대댓글을 정렬하기 위한 순서이자 묶어주기 위한 그룹 대댓글의 경우 같은 order로 묶고 생성 날짜로 정렬한다')),
                ('comment_contents', models.TextField(help_text='댓글 내용')),
                ('comment_date', models.DateTimeField(auto_now_add=True, help_text='댓글 작성한 날짜')),
                ('comment_isreply', models.BooleanField(help_text='답글 여부 확인')),
                ('comment_isdelete', models.BooleanField(default=False, help_text='삭제 여부 확인')),
                ('comment_editor', models.ForeignKey(help_text='댓글 작성자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='main.bloginfo')),
                ('comment_post', models.ForeignKey(help_text='댓글이 달린 포스트', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.postcontents')),
            ],
        ),
    ]
