# Generated by Django 5.1.4 on 2024-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('media_index', models.IntegerField(auto_created=True, help_text='미디어 인덱스', primary_key=True, serialize=False)),
                ('media_id', models.CharField(help_text='미디어 id', max_length=100)),
                ('media_name', models.CharField(help_text='미디어 파일 이름름', max_length=100)),
                ('media_date', models.DateTimeField(auto_now=True, help_text='미디어가 업로드된 날짜')),
                ('media_contents', models.TextField(help_text='미디어 데이터, base64로 인코딩해서 넣을듯')),
            ],
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('comment_index', models.IntegerField(auto_created=True, help_text='댓글 인덱스', primary_key=True, serialize=False)),
                ('comment_id', models.CharField(help_text='댓글 id', max_length=100)),
                ('comment_postadress', models.CharField(help_text='댓글이 달린 포스트 주소', max_length=50)),
                ('comment_editor_uid', models.CharField(help_text='댓글 작성자 uid', max_length=20)),
                ('comment_contents', models.TextField(help_text='댓글 내용', null=True)),
                ('comment_date', models.DateTimeField(auto_now=True, help_text='댓글 작성한 날짜')),
                ('comment_isreply', models.BooleanField(help_text='답글 여부 확인')),
                ('comment_replyto', models.CharField(help_text='답글 주소 id', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostContents',
            fields=[
                ('post_index', models.IntegerField(auto_created=True, help_text='블로그 포스트 인덱스', primary_key=True, serialize=False)),
                ('post_id', models.CharField(help_text='블로그 포스트 id', max_length=100)),
                ('post_title', models.CharField(db_index=True, help_text='블로그 포스트 제목 필드', max_length=20)),
                ('post_contents', models.TextField(help_text='블로그 포스트 내용 필드', null=True)),
                ('post_date', models.DateTimeField(auto_now=True, help_text='블로그 포스트 날짜')),
                ('post_editdate', models.DateTimeField(auto_now=True, help_text='블로그 포스트 수정된 날짜')),
                ('post_editor_uid', models.CharField(help_text='포스트 작성자 uid', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
