# Generated by Django 5.2.7 on 2025-10-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='slug',
            field=models.SlugField(blank=True, help_text='사용자 ID를 슬러그로 받음', max_length=100, unique=True),
        ),
    ]
