# Generated by Django 5.2.7 on 2025-10-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bloginfo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='카테고리 이름을 슬러그로 받음', max_length=100),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='slug',
            field=models.SlugField(blank=True, help_text='포스트 제목을 슬러그로 받음', max_length=100),
        ),
    ]
