# Generated by Django 5.1.4 on 2024-12-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mediacontent_postcomments_postcontents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='media_contents',
            field=models.TextField(help_text='미디어 데이터, base64로 인코딩해서 넣을듯, 사진이면 Webp를 적용하고 싶음'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, help_text='댓글 작성한 날짜'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment_id',
            field=models.CharField(help_text='댓글 id 형식은 GUID + 숫자 4자리', max_length=100),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment_replyto',
            field=models.CharField(help_text='답글 주소 id, 댓글 ID를 여기다 넣음', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, help_text='블로그 포스트 날짜'),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_id',
            field=models.CharField(help_text='블로그 포스트 id 아마 GUID로 설정될 듯', max_length=100),
        ),
    ]
