# Generated by Django 5.1.4 on 2025-09-24 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bloginfo_blog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='post_editdate',
            field=models.DateTimeField(blank=True, help_text='블로그 포스트 수정된 날짜, 해당 필드에 값 유무로 포스트 수정 여부를 판단함', null=True),
        ),
    ]
