# Generated by Django 5.1.4 on 2024-12-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mediacontent_media_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='comment_replyto',
            field=models.CharField(blank=True, help_text='답글 주소 id, 댓글 ID를 여기다 넣음', max_length=100, null=True),
        ),
    ]
