# Generated by Django 5.2.7 on 2025-10-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_blogcategory_slug_alter_postcontents_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontents',
            name='title_align',
            field=models.CharField(choices=[('left', '왼쪽'), ('center', '가운데'), ('right', '오른쪽')], default='left', help_text='포스트 제목 정렬', max_length=10),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_category',
            field=models.ForeignKey(blank=True, help_text='포스트가 속한 카테고리', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='main.blogcategory'),
        ),
    ]
