# Generated by Django 5.2.7 on 2025-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_postcontents_title_align_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='comment_index',
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment_id',
            field=models.AutoField(help_text='댓글 id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_id',
            field=models.AutoField(help_text='블로그 포스트 id', primary_key=True, serialize=False),
        ),
    ]
