# Generated by Django 5.1.4 on 2025-01-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_postcomments_comment_replyto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='post_contents',
            field=models.TextField(help_text='블로그 포스트 내용 필드'),
        ),
    ]
