# Generated by Django 5.2.7 on 2025-10-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_postcomments_comment_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/profile_created_by_Gemini.webp', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='comment_order',
            field=models.IntegerField(default=1, help_text='댓글/답글을 정렬하기 위한 순서이자 묶어주기 위한 그룹, 답글의 경우 같은 order로 묶고 생성 날짜로 정렬한다'),
        ),
    ]
