# Generated by Django 5.1.4 on 2025-01-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_postcontents_post_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='comment_contents',
            field=models.TextField(help_text='댓글 내용'),
        ),
    ]
