# Generated by Django 5.2.7 on 2025-11-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customuser_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='mention',
            field=models.ForeignKey(blank=True, help_text='@멘션', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentioned_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
