# Generated by Django 5.1.4 on 2025-01-07 00:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_postcontents_post_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='post_contents',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
