# Generated by Django 5.2.7 on 2025-11-03 23:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_postcomments_mention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('like', 'Like')], help_text='알림 타입: 좋아요, 댓글 등등', max_length=20)),
                ('notification_message', models.TextField(help_text='알림 내용')),
                ('notification_url', models.CharField(blank=True, help_text='알림 바로가기 url', max_length=255)),
                ('notification_is_read', models.BooleanField(default=False, help_text='알림 읽었는지 여부')),
                ('notification_created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='만들어진 시간')),
                ('notification_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('notification_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-notification_created_at'],
            },
        ),
    ]
