# Generated by Django 5.1.4 on 2025-01-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_postcontents_post_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcontents',
            name='post_contents',
            field=models.TextField(help_text='블로그 포스트 내용 필드'),
        ),
    ]
