# Generated by Django 5.2.7 on 2025-11-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontents',
            name='post_view_count',
            field=models.PositiveIntegerField(default=0, help_text='조회수 값'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_created_at', models.DateTimeField(auto_now_add=True)),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.postcomments')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('like_user', 'like_post')},
            },
        ),
    ]
