# Generated by Django 5.1.4 on 2025-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_postcontents_post_contents'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('category_index', models.IntegerField(auto_created=True, help_text='카테고리 인덱스', primary_key=True, serialize=False)),
                ('category_id', models.CharField(help_text='카테고리 id', max_length=100)),
                ('category_for', models.CharField(help_text='카테고리가 적용될 블로그 주소', max_length=100)),
                ('category_isdepth', models.BooleanField(help_text='뎁스가 적용된 카테고리 여부 확인')),
                ('category_depth_for', models.CharField(help_text='뎁스가 적용된 카테고리의 부모 카테고리 id', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.CharField(help_text='블로그 id https://ex.com/blog/-------/', max_length=100)),
                ('blog_title', models.CharField(db_index=True, help_text='블로그 제목', max_length=20)),
                ('blog_user', models.CharField(help_text='블로그 uid', max_length=20)),
            ],
        ),
    ]
