# Generated by Django 5.1.4 on 2025-01-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_blogcategory_bloginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_name',
            field=models.CharField(db_index=True, default='내 글', help_text='카테고리 제목', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category_depth_for',
            field=models.CharField(blank=True, help_text='뎁스가 적용된 카테고리의 부모 카테고리 id', max_length=100, null=True),
        ),
    ]
