# Generated by Django 5.2.7 on 2025-11-04 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_postcontents_post_view_count_postlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='like_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.postcontents'),
        ),
    ]
