# Generated by Django 5.1.4 on 2025-01-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_blogcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontents',
            name='post_category_for',
            field=models.CharField(default='dd', help_text='카테고리 id', max_length=100),
        ),
    ]
