# Generated by Django 5.2.7 on 2025-11-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_postlike_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='blog_created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 5, 21, 56, 49, 22378), help_text='블로그 포스트 날짜'),
            preserve_default=False,
        ),
    ]
