# Generated by Django 5.2.7 on 2025-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_bloginfo_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcontents',
            name='post_thumbnail',
            field=models.ImageField(blank=True, help_text='포스트 썸네일', null=True, upload_to='posts/thumbnails/'),
        ),
    ]
