# Generated by Django 5.1.4 on 2025-01-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_postcontents_post_category_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='comment_order',
            field=models.IntegerField(default=1, help_text='댓글/대댓글을 정렬하기 위한 순서'),
        ),
    ]
