# Generated by Django 5.2.7 on 2025-11-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_postcontents_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloginfo',
            name='blog_description',
            field=models.CharField(blank=True, default='새로운 블로그입니다.', help_text='블로그 소개', max_length=100, null=True),
        ),
    ]
