# Generated by Django 5.2.8 on 2025-11-10 17:11

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_bloginfo_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_depth_for',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_index',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_isdepth',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='category_sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.blogcategory'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.bloginfo'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='category_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_created_date',
            field=models.DateTimeField(auto_now_add=True, help_text='블로그 만들어진 날짜'),
        ),
    ]
