# Generated by Django 5.2.8 on 2025-11-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_blogcategory_category_depth_for_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['tree_id', 'lft']},
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='category_sort_order',
        ),
    ]
