# Generated by Django 5.2.8 on 2025-11-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
