# Generated by Django 5.2.8 on 2025-11-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_blogcategory_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ['category_order']},
        ),
        migrations.AlterField(
            model_name='postcontents',
            name='post_category',
            field=models.ForeignKey(blank=True, help_text='포스트가 속한 카테고리', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.blogcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategory',
            unique_together={('category_for', 'slug')},
        ),
    ]
