# Generated by Django 5.2.8 on 2025-11-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_isopen',
            field=models.BooleanField(default=False, help_text='카테고리를 펼침 여부 결정'),
        ),
    ]
